### ISSUE TITLE
Cannot install on Ubuntu 

### ISSUE THREAD

**Issue by paul-ridgway** [jaytohe/aerofnkeys#1]
Following the README led to the error below:

```
~ on ☁️  eu-west-2 
❯ sudo modprobe fn_keys_mod
[sudo] password for paul: 
modprobe: ERROR: could not insert 'fn_keys_mod': Operation not permitted

~ on ☁️  eu-west-2 took 2s 
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

I plan to try and figure it out when I get time, and will propose a README update if I can.

**Comment by jaytohe** [comment]
Googling your issue reveals that it probably occurs due to secure boot being enabled. See [here](https://unix.stackexchange.com/a/543580)

**Comment by paul-ridgway** [comment]
Thanks, I'll check that out
